# Generated by Django 6.0.6 on 2026-06-16 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibicion',
            name='costo_produccion',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de producción'),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='duracion_meses',
            field=models.IntegerField(verbose_name='Duración en meses'),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.guiamuseo'),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='tematica',
            field=models.CharField(max_length=100, verbose_name='Temática'),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='titulo_exhibicion',
            field=models.CharField(max_length=150, verbose_name='Título de exhibición'),
        ),
        migrations.AlterField(
            model_name='guiamuseo',
            name='anios_experiencia_guia',
            field=models.IntegerField(verbose_name='Años de experiencia como guía'),
        ),
        migrations.AlterField(
            model_name='guiamuseo',
            name='idiomas_hablados',
            field=models.CharField(max_length=200, verbose_name='Idiomas hablados'),
        ),
        migrations.AlterField(
            model_name='guiamuseo',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.museo'),
        ),
        migrations.AlterField(
            model_name='guiamuseo',
            name='nombre_completo',
            field=models.CharField(max_length=150, verbose_name='Nombre completo del guía'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='anio_fundacion',
            field=models.IntegerField(verbose_name='Año de fundación'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad del museo'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del museo'),
        ),
    ]
